### ISSUE TITLE
Fails to generate types every second run (when types are already in dist directory)

### ISSUE THREAD

**Issue by dlitsman** [qmhc/vite-plugin-dts#254]
### Describe the bug

When dist directory already has types, vite-plugin-dts removes existing types but fails to generate new ones. It seems similar to https://github.com/qmhc/vite-plugin-dts/issues/203 however I can still repro on 3.3.1. So I guess not duplicate as different major version and based on comments it should be fixes in 3.0

https://github.com/qmhc/vite-plugin-dts/assets/963490/97421c10-7c3a-4202-9639-a7d261adc0bd

### Reproduction

https://github.com/dlitsman/react-wake-lock/tree/feature/vite-build

### Steps to reproduce

1. git clone git@github.com:dlitsman/react-wake-lock.git
2. cd react-wake-lock
3. git checkout feature/vite-build
4. npm install
5. npm run build (success, types generated)
6. npm run build (again, removes types and no new types created)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 523.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - ~/.nvm/versions/node/v20.4.0/bin/node
    npm: 9.7.2 - ~/.nvm/versions/node/v20.4.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.1
  npmPackages:
    vite: ^4.4.7 => 4.4.7 
    vite-plugin-dts: ^3.3.1 => 3.3.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
The previous fix broke the generation of map files, so I decided to revert the previous fix and seek an alternative solution. 

Therefore, I reopened the issue.

You can use version `3.5.1` to bypass this issue temporarily (but it cannot generate map files).

**Comment by qmhc** [comment]
It's due to TypeScript version. In the latest version it seems that the issue has been resolved.

**Comment by thiemok** [comment]
I'm still seeing this issue, or a similar issue, with version `3.6.3`. My logs indicate that typescript `5.0.4` is used, which the linked comment suggests as a potential cause for the issue. Am I maybe missing something?

**Comment by qmhc** [comment]
@thiemok You can try to provide a minimum reproduction and create a new issue.

**Comment by thiemok** [comment]
The issue is frankly very intermittent for me and I was able to avoid it by downgrading to `3.5.1`. Before I dive into trying to get it reproduced consistently, can you confirm that typescript `5.0.4` being used by the plugin is expected behavior on version `3.6.3`?
